kind: live
title: fastchat

# other files from https://github.com/lm-sys/FastChat

defaults:
  life_span: 5d

images:
  fastchat:
    ref: image://cato-gpu-poc/yevheniisemendiak/fastchat:v1
    dockerfile: $[[ flow.workspace ]]/docker/Dockerfile
    context: $[[ flow.workspace ]]/

volumes:
  cache:
    remote: storage:$[[ flow.project_id ]]/cache
    mount: /root/.cache/huggingface
    local: cache
  project:
    remote: storage:$[[ flow.project_id ]]
    mount: /project
    local: .
  tests:
    remote: storage:$[[ flow.project_id ]]/tests
    mount: /project/tests
    local: tests

jobs:
  controller:
    image: ${{ images.fastchat.ref }}
    name: controller
    preset: cpu-small
    http_port: "21001"
    detach: true
    bash: |
      python3.9 -m fastchat.serve.controller --host 0.0.0.0 --port 21001

  worker:
    image: ${{ images.fastchat.ref }}
    volumes:
      - ${{ volumes.cache.ref_rw }}
    env:
      FASTCHAT_CONTROLLER_URL: http://${{ inspect_job('controller').internal_hostname_named }}:21001
    preset: gpu-medium
    detach: true
    multi: true
    params:
      model: vicuna-13b-v1.3
    bash: |
      worker_hostname=${NEURO_JOB_INTERNAL_HOSTNAME_NAMED/21f085730c/${{ project.project_name }}}
      controller_hostname=${FASTCHAT_CONTROLLER_URL/21f085730c/${{ project.project_name }}}
      python3.9 -m fastchat.serve.model_worker \
        --model-name ${{ params.model }} \
        --model-path lmsys/${{ params.model }} \
        --worker-address http://$worker_hostname:21002 \
        --controller-address $controller_hostname \
        --host 0.0.0.0 --port 21002 --num-gpus 2 #--load-8bit

  api:
    image: ${{ images.fastchat.ref }}
    env:
      FASTCHAT_CONTROLLER_URL: http://${{ inspect_job('controller').internal_hostname_named }}:21001
    http_port: "8000"
    name: api
    preset: cpu-small
    detach: true
    bash: |
      controller_hostname=${FASTCHAT_CONTROLLER_URL/21f085730c/${{ project.project_name }}}
      python3.9 -m fastchat.serve.openai_api_server \
        --controller-address $controller_hostname \
        --host 0.0.0.0 --port 8000

  web:
    image: ${{ images.fastchat.ref }}
    env:
      FASTCHAT_CONTROLLER_URL: http://${{ inspect_job('controller').internal_hostname_named }}:21001
    http_port: "8000"
    preset: cpu-small
    name: web
    detach: true
    browse: true
    bash: |
      controller_hostname=${FASTCHAT_CONTROLLER_URL/21f085730c/${{ project.project_name }}}
      python3.9 -m fastchat.serve.gradio_web_server \
        --controller-url $controller_hostname \
        --model-list-mode reload \
        --host 0.0.0.0 --port 8000

  locust:
    image: locustio/locust
    http_port: 8089
    preset: cpu-small
    detach: True
    name: locust
    env:
      NEURO_TOKEN: secret:NEURO_TOKEN
    volumes:
      - ${{ volumes.tests.ref_ro }}
    cmd: -f ${{ volumes.tests.mount }}/locustfile.py -H http://${{ inspect_job('api').internal_hostname_named }}:8000
